### ISSUE TITLE
command in readme not working?

### ISSUE THREAD

**Issue by dimitarg** [pires/netty-tcnative-alpine#1]
I don't really understand why, but running

```
docker run -v `pwd`/binaries pires/netty-tcnative-alpine
```

left that directory empty after the container was run.
Im running ubuntu 16.04 with docker 1.11.1

What worked for me was 

```
docker run -v `pwd`/binaries:/output pires/netty-tcnative-alpine
```

**Comment by pires** [comment]
@dimitarg thank you it seems I screwed up the docs. You found the correct way to do it ;)

**Comment by dimitarg** [comment]
Thanks for your work. Successfully moved to 4.1.1 final with this repo

**Comment by pires** [comment]
By any chance, are you using Spring Boot? Having a hard time getting the `boringssl-static` binary to run there. It's in the classpath, but it still won't load.

If I do it manually with a simple app JAR + `-classpath` argument, it works.

**Comment by dimitarg** [comment]
Nope, sorry. We're a very lean setup with just a main class and entry point via https://github.com/Transmode/gradle-docker. Almost no external dependencies + homegrown framework

**Comment by pires** [comment]
It seems [Tomcat is to blame](https://github.com/netty/netty-tcnative/issues/136). I've since moved to Undertow but now the JVM crashes:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcf6e53fb51, pid=6, tid=0x00007fcf58002ab0
#
# JRE version: OpenJDK Runtime Environment (8.0_92-b14) (build 1.8.0_92-internal-alpine-r1-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-musl-x86_64.so.1+0x4fb51]  memcpy+0x11
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# //hs_err_pid6.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by pires** [comment]
_Update_: it sometimes crashes, sometimes don't.
