### ISSUE TITLE
Upstream netty-tcnative-boringssl-static works on Alpine

### ISSUE THREAD

**Issue by ejona86** [pires/netty-tcnative-alpine#11]
This is just FYI, but I did some recent testing on Alpine and I discovered that netty-tcnative-boringssl-static works without issue on standard Alpine.

For `openjdk:8-jre-alpine`, I ran `apk update && apk add libc6-compat` while generating the docker image.

For `alpine:latest`, I ran `apk update && apk add openjdk8-jre-base libc6-compat`.

`adoptopenjdk/openjdk8:alpine-slim` and `adoptopenjdk/openjdk11:alpine-slim` worked out-of-the-box.

**Comment by pires** [comment]
Thank you @ejona86. I think I'm going to archive this repo and point out the information you shared above on top of the `README.md`. WDYT?
