### ISSUE TITLE
Publish artifacts to maven

### ISSUE THREAD

**Issue by rdsubhas** [pires/netty-tcnative-alpine#3]
Thanks for your work! Now that these files can be easily generated, it would be nice to also upload those built binaries 😄 Travis-CI already supports [running docker builds](https://docs.travis-ci.com/user/docker/) so would be nice to add a `.travis.yml` that does a docker build and maven publish. What do you think?

**Comment by pires** [comment]
For Maven artifacts to become available, two things are needed:
1. A groupId, and in this case I can't control netty-tcnative one and would have to use something like `com.github.pires.netty` and artifactIds `netty-tcnative-xxx`.
2. Automatically sign artifacts with some key . For other projects of mine, I usually do this release process manually with my own private keys. I'm not comfortable with doing that with CI-as-a-Service.

Anyway, I could, however, expose the binaries as releases here on Github. Would that work for you?

**Comment by rdsubhas** [comment]
@pires Let me see if there are other options...
