### ISSUE TITLE
openssl source package not found

### ISSUE THREAD

**Issue by hleeanexinet** [pires/netty-tcnative-alpine#4]
Openssl 1.0.2h is downloaded to openssl-static/target/old/1.0.2/ directory, but the ant build file looks for the file under openssl-static/target/. Because of this, building the openssl-static module fails. The easy fix would be to upgrade openssl to 1.0.2k. A better solution would be to make sure that the file is downloaded to the right location.

**Comment by pires** [comment]
@hleeanexinet this seems to have been [updated upstream](https://github.com/netty/netty-tcnative/blob/master/pom.xml#L68). I'm trying to update this image but Alpine CDN is down so I can't try it out before pushing the new changes.

**Comment by pires** [comment]
Another problem, during the build ant tries to download artifacts from openssl.org FTP and it fails.

**Comment by pires** [comment]
`libressl-static` won't compile because of:
```
[exec] make[1]: Leaving directory '/netty-tcnative/libressl-static/target/libressl-2.4.5/crypto'
     [exec] compat/getentropy_linux.c:31:26: fatal error: linux/sysctl.h: No such file or directory
     [exec]  #include <linux/sysctl.h>
     [exec]                           ^
     [exec] compilation terminated.
     [exec] make[1]: *** [Makefile:3615: compat/getentropy_linux.lo] Error 1
     [exec] make: *** [Makefile:451: all-recursive] Error 1
```
