### ISSUE TITLE
libressl-static doesn't build.

### ISSUE THREAD

**Issue by pires** [pires/netty-tcnative-alpine#5]
```
[exec] make[1]: Leaving directory '/netty-tcnative/libressl-static/target/libressl-2.4.5/crypto'
     [exec] compat/getentropy_linux.c:31:26: fatal error: linux/sysctl.h: No such file or directory
     [exec]  #include <linux/sysctl.h>
     [exec]                           ^
     [exec] compilation terminated.
     [exec] make[1]: *** [Makefile:3615: compat/getentropy_linux.lo] Error 1
     [exec] make: *** [Makefile:451: all-recursive] Error 1
```

**Comment by anuraaga** [comment]
I found that if you add linux-headers to the apk install command, libressl will build fine :)

**Comment by pires** [comment]
@anuraaga PR? :)

**Comment by pires** [comment]
Thanks!

**Comment by kaushalmodi** [comment]
Hello guys,

While searching for the same error message, I landed up on this message. I am seeing the same error on Travis CI which runs Ubuntu 14: https://travis-ci.org/kaushalmodi/hello_musl/builds/440319409#L1332.

I installed `sudo apt install linux-headers-$(uname -r)`, but that didn't help. Would you guys be able to help out? 

I need to compile static libressl with musl.
