### ISSUE TITLE
openssl-static tests fail since libapr 1.5.2 no longer exists in http://www.us.apache.org/dist/apr/

### ISSUE THREAD

**Issue by Rich-Carreiro-Imprivata** [pires/netty-tcnative-alpine#8]
The `openssl-static` tests fail because the maven build happening in the container is unable to download `apr-1.5.2.tar.gz` from http://www.us.apache.org/dist/apr (and it truly is no longer there).

So it looks like the `netty-tcnative` version specified in `Dockerfile` needs to be updated to a version of `netty-tcnative` that uses `apr-1.6.2` in its build.

**Comment by pires** [comment]
You can pass the version you want to compile as an environment variable. See https://github.com/pires/netty-tcnative-alpine#bootstrap-builder.

This no longer is of use to me but feel free to open a PR that updates versions.
